Added download button
aparcar/devices pull request #8
Opened 2021-07-12 10:41 UTC by Aditi-1400

- Added the download file button
- Removed react-select for now due to delayed state update

2021-07-18 12:56 UTC, aparcar requested changes

2021-07-18 12:56 UTC, aparcar commented on form/src/App.js
> +  // };
Please see your other PR on how to deal with this. 1. have it in a different commit/PR and second don't *comment* code but remove it, it stays in the git log anyway.

2021-07-18 12:56 UTC, aparcar commented on form/src/App.js
> +    const name = formData.vendor+formData.model+formData.variant+".yaml"
This is mostly fine, however please modify the name to follow the `device_id`. It's defined by the following pseudo code:

```
filename = "${ vendor.toLowerCase() }_${ model.toLowerCase()"
if (variant != "") {
  filename = filename + '-' + variant.toLowerCase()
}
filename = filename.replace(' ', '-')
filename = filename.replaceNonAsciiChars()
```

So, all lowercase, no spaces, only ASCII chars and attach the `variant` only if defined. Currently the filename would become something like `TP-Link Router 5000undefined.yml` while it should be `tp-link_router-5000.yaml` and `Foobar Test 4000 v3` should become `foobar_test-4000-v3`.

2021-07-19 20:20 UTC, aparcar commented
Please rebase this PR and implement the filename change I suggested.

2021-07-20 08:19 UTC, aparcar commented
Thanks for the update! The `variant` handling is still incomplete but looks good apart from that:
![image](https://user-images.githubusercontent.com/16000931/126286735-c460169d-d294-4b3e-967a-c580812b1bd0.png)

2021-07-20 08:23 UTC, aparcar commented
This commit contains a merge commit which can be removed via rebasing. I used the following commands to do so, please try locally and update the PR:

```
git rebase main # this gives an error message of things not lining up
git diff # check out what's actually wrong
vim form/src/App.js # here is the issue, use whatever editor you like, fix the file
git add form/src/App.js
git rebase --continue
git show # just to verify everything is in shape
```

Let me know if there are issues

2021-07-20 08:37 UTC, Aditi-1400 commented
I've made the changes, Let me know if there are any other issues!

2021-07-20 08:50 UTC, aparcar commented on form/src/App.js
> +      name = name +'-'+ variant + ".yaml";
the `yaml` suffix is only added if a variant is set, it should be added in any case.

2021-07-20 09:03 UTC, aparcar commented
Excellent, thanks!

2021-07-20 09:03 UTC, merged