Added autocomplete for CPU
aparcar/devices pull request #9
Opened 2021-07-14 12:04 UTC by Aditi-1400

- Added CPU autocomplete functionality
- Removed react-select due to delayed state change

2021-07-18 12:42 UTC, aparcar commented
I tried this locally but receive the following error message, how did you test this?
![image](https://user-images.githubusercontent.com/16000931/126067503-f19f93d3-13d1-48d0-8e0a-10f20b2d633a.png)

2021-07-18 12:46 UTC, aparcar requested changes

2021-07-18 12:46 UTC, aparcar commented on form/src/App.js
> +  // };
You're mixing things within a single commit again. These changes are unrelated but you still commit them in a single run, resulting in one PR isn't compatible with the other. Use three PRs instead and if they depend on one another, mention that in the description.

2021-07-18 12:46 UTC, aparcar commented on form/src/App.js
>  import Form from "@rjsf/bootstrap-4";
Please start using a code linter which automatically makes sure the code style is the same everywhere. In this example there are partly spaces and partly not. Please create another PR which applies e.g. https://prettier.io/ everywhere.

2021-07-18 12:46 UTC, aparcar commented on form/src/App.js
> +  // };
Instead of *commenting* the code, please remove it. It'll still be in the git history to be looked at for future reference.

2021-07-20 09:12 UTC, Aditi-1400 commented
I am unable to understand why the validate metadata is failing! Also, I tested it simply by `yarn start`, are you still getting that error?

2021-07-22 14:15 UTC, aparcar commented
Please make a clean copy of the git repository and try again.

2021-07-23 20:26 UTC, aparcar commented
Tried again and with an updates `schema.json` it worked fine. Thanks! I'll update the CI to automatically add things to schema YAML files.

2021-07-23 20:27 UTC, merged